services:
  - type: web
    name: algoritmos-backend
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/algoritmos-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
    rootDir: .
